version: "3.9"
services:
  mysql:
    container_name: mysql_container
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: five_heads_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - .:/var/lib/mysql
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    networks:
      - app

  backend:
    container_name: web_container
    image: five_heads_backend
    build:
      dockerfile: CitationParser.Api/Dockerfile
    command: dotnet CitationParser.Api.dll
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:5000;"
    ports:
      - "5000:5000"
    working_dir: /app
    restart: unless-stopped
    networks:
      - app
    depends_on:
      - mysql

  logger:
    container_name: seq
    image: lowartem/seq
    ports:
      - "5341:80"
    restart: unless-stopped
    networks:
      - app

networks:
  app:
    driver: bridge
