// <auto-generated />
using System;
using CitationParser.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitationParser.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("AuthorPublication", b =>
                {
                    b.Property<int>("IdAuthors")
                        .HasColumnType("int");

                    b.Property<int>("IdPublications")
                        .HasColumnType("int");

                    b.HasKey("IdAuthors", "IdPublications");

                    b.ToTable("AuthorPublication");
                });

            modelBuilder.Entity("CitationParser.Data.Model.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("authors");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8_general_ci");
                });

            modelBuilder.Entity("CitationParser.Data.Model.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("cities");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8_general_ci");
                });

            modelBuilder.Entity("CitationParser.Data.Model.Editor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("editors");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8_general_ci");
                });

            modelBuilder.Entity("CitationParser.Data.Model.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ArticleNumber")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("articleNumber");

                    b.Property<string>("Country")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("country");

                    b.Property<string>("DataStorage")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dataStorage");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("DateOfRegistration")
                        .HasColumnType("date")
                        .HasColumnName("dateOfRegistration");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Doi")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DOI");

                    b.Property<string>("Information")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("information");

                    b.Property<string>("InformationAboutPublication")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("informationAboutPublication");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Number")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("number");

                    b.Property<string>("NumberOfPages")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("numberOfPages");

                    b.Property<int?>("NumberOfVolumes")
                        .HasColumnType("int")
                        .HasColumnName("numberOfVolumes");

                    b.Property<string>("PageNumbers")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("pageNumbers");

                    b.Property<string>("ParallelSourceTitle")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("parallelSourceTitle");

                    b.Property<string>("ParallelTitle")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("parallelTitle");

                    b.Property<string>("PlaceOfRegistration")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("placeOfRegistration");

                    b.Property<string>("PublishingHouse")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("publishingHouse");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("registrationNumber");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("title");

                    b.Property<string>("TitleOfSource")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("titleOfSource");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.Property<string>("Url")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("URL");

                    b.Property<int?>("VolumeNumber")
                        .HasColumnType("int")
                        .HasColumnName("volumeNumber");

                    b.Property<string>("Year")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TypeId" }, "FK_types_publications");

                    b.ToTable("publications");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8_general_ci");
                });

            modelBuilder.Entity("CitationParser.Data.Model.ScientificCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("country");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("FinishDate")
                        .HasColumnType("date")
                        .HasColumnName("finish_date");

                    b.Property<int>("IdCity")
                        .HasColumnType("int")
                        .HasColumnName("id_city");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("NumberOfVolumes")
                        .HasColumnType("int")
                        .HasColumnName("numberOfVolumes");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("title");

                    b.Property<int?>("VolumeNumber")
                        .HasColumnType("int")
                        .HasColumnName("volumeNumber");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("scientific_collections");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8_general_ci");
                });

            modelBuilder.Entity("CitationParser.Data.Model.TypesOfPublication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("types_of_publications");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8_general_ci");
                });

            modelBuilder.Entity("CitationParser.Data.Model.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("universities");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8_general_ci");
                });

            modelBuilder.Entity("CityPublication", b =>
                {
                    b.Property<int>("IdCities")
                        .HasColumnType("int");

                    b.Property<int>("IdPublications")
                        .HasColumnType("int");

                    b.HasKey("IdCities", "IdPublications");

                    b.ToTable("CityPublication");
                });

            modelBuilder.Entity("EditorScientificCollection", b =>
                {
                    b.Property<int>("IdEditors")
                        .HasColumnType("int");

                    b.Property<int>("IdScientificCollections")
                        .HasColumnType("int");

                    b.HasKey("IdEditors", "IdScientificCollections");

                    b.ToTable("EditorScientificCollection");
                });

            modelBuilder.Entity("PublicationUniversity", b =>
                {
                    b.Property<int>("IdPublications")
                        .HasColumnType("int");

                    b.Property<int>("IdUniversities")
                        .HasColumnType("int");

                    b.HasKey("IdPublications", "IdUniversities");

                    b.ToTable("PublicationUniversity");
                });

            modelBuilder.Entity("PublicationsToAuthor", b =>
                {
                    b.Property<int>("IdPublications")
                        .HasColumnType("int")
                        .HasColumnName("id_Publications");

                    b.Property<int>("IdAuthors")
                        .HasColumnType("int")
                        .HasColumnName("id_Authors");

                    b.HasKey("IdPublications", "IdAuthors")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdAuthors" }, "FK_authors_to_publications");

                    b.ToTable("publications_to_authors", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8_general_ci");
                });

            modelBuilder.Entity("PublicationsToCity", b =>
                {
                    b.Property<int>("IdPublications")
                        .HasColumnType("int")
                        .HasColumnName("id_Publications");

                    b.Property<int>("IdCities")
                        .HasColumnType("int")
                        .HasColumnName("id_cities");

                    b.HasKey("IdPublications", "IdCities")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdCities" }, "FK_Sities");

                    b.ToTable("publications_to_cities", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8_general_ci");
                });

            modelBuilder.Entity("PublicationsToUniversity", b =>
                {
                    b.Property<int>("IdPublications")
                        .HasColumnType("int")
                        .HasColumnName("id_Publications");

                    b.Property<int>("IdUniversities")
                        .HasColumnType("int")
                        .HasColumnName("id_Universities");

                    b.HasKey("IdPublications", "IdUniversities")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdUniversities" }, "FK_universities_to_publications");

                    b.ToTable("publications_to_universities", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8_general_ci");
                });

            modelBuilder.Entity("ScientificCollectionUniversity", b =>
                {
                    b.Property<int>("IdScientificCollections")
                        .HasColumnType("int");

                    b.Property<int>("IdUniversities")
                        .HasColumnType("int");

                    b.HasKey("IdScientificCollections", "IdUniversities");

                    b.ToTable("ScientificCollectionUniversity");
                });

            modelBuilder.Entity("ScientificCollectionsToEditor", b =>
                {
                    b.Property<int>("IdScientificCollections")
                        .HasColumnType("int")
                        .HasColumnName("id_scientific_collections");

                    b.Property<int>("IdEditors")
                        .HasColumnType("int")
                        .HasColumnName("id_editors");

                    b.HasKey("IdScientificCollections", "IdEditors")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdEditors" }, "FK_scientific_collections_to_editors_editors");

                    b.ToTable("scientific_collections_to_editors", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8_general_ci");
                });

            modelBuilder.Entity("ScientificCollectionsToUniversity", b =>
                {
                    b.Property<int>("IdScientificCollections")
                        .HasColumnType("int")
                        .HasColumnName("id_scientific_collections");

                    b.Property<int>("IdUniversities")
                        .HasColumnType("int")
                        .HasColumnName("id_universities");

                    b.HasKey("IdScientificCollections", "IdUniversities")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdUniversities" }, "FK_scientific_collections_to_universities_universities");

                    b.ToTable("scientific_collections_to_universities", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8_general_ci");
                });

            modelBuilder.Entity("CitationParser.Data.Model.Publication", b =>
                {
                    b.HasOne("CitationParser.Data.Model.TypesOfPublication", "Type")
                        .WithMany("Publications")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_types_publications");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PublicationsToAuthor", b =>
                {
                    b.HasOne("CitationParser.Data.Model.Author", null)
                        .WithMany()
                        .HasForeignKey("IdAuthors")
                        .IsRequired()
                        .HasConstraintName("FK_authors_to_publications");

                    b.HasOne("CitationParser.Data.Model.Publication", null)
                        .WithMany()
                        .HasForeignKey("IdPublications")
                        .IsRequired()
                        .HasConstraintName("FK_Publications_to_authors");
                });

            modelBuilder.Entity("PublicationsToCity", b =>
                {
                    b.HasOne("CitationParser.Data.Model.City", null)
                        .WithMany()
                        .HasForeignKey("IdCities")
                        .IsRequired()
                        .HasConstraintName("FK_Sities");

                    b.HasOne("CitationParser.Data.Model.Publication", null)
                        .WithMany()
                        .HasForeignKey("IdPublications")
                        .IsRequired()
                        .HasConstraintName("FK_Publications");
                });

            modelBuilder.Entity("PublicationsToUniversity", b =>
                {
                    b.HasOne("CitationParser.Data.Model.Publication", null)
                        .WithMany()
                        .HasForeignKey("IdPublications")
                        .IsRequired()
                        .HasConstraintName("FK_publications_to_universities");

                    b.HasOne("CitationParser.Data.Model.University", null)
                        .WithMany()
                        .HasForeignKey("IdUniversities")
                        .IsRequired()
                        .HasConstraintName("FK_universities_to_publications");
                });

            modelBuilder.Entity("ScientificCollectionsToEditor", b =>
                {
                    b.HasOne("CitationParser.Data.Model.Editor", null)
                        .WithMany()
                        .HasForeignKey("IdEditors")
                        .IsRequired()
                        .HasConstraintName("FK_scientific_collections_to_editors_editors");

                    b.HasOne("CitationParser.Data.Model.ScientificCollection", null)
                        .WithMany()
                        .HasForeignKey("IdScientificCollections")
                        .IsRequired()
                        .HasConstraintName("FK_scientific_collections_to_editros_scientific_collections");
                });

            modelBuilder.Entity("ScientificCollectionsToUniversity", b =>
                {
                    b.HasOne("CitationParser.Data.Model.ScientificCollection", null)
                        .WithMany()
                        .HasForeignKey("IdScientificCollections")
                        .IsRequired()
                        .HasConstraintName("FK_scientific_collections_to_universities_scientific_collections");

                    b.HasOne("CitationParser.Data.Model.University", null)
                        .WithMany()
                        .HasForeignKey("IdUniversities")
                        .IsRequired()
                        .HasConstraintName("FK_scientific_collections_to_universities_universities");
                });

            modelBuilder.Entity("CitationParser.Data.Model.TypesOfPublication", b =>
                {
                    b.Navigation("Publications");
                });
#pragma warning restore 612, 618
        }
    }
}
